spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quizServiceDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8090